### ISSUE TITLE
Possible compat issue

### ISSUE THREAD

**Issue by Sunconure11** [TheRealHenHen/Bamboo-Combat#1]
@TheRealHenHen 

I was told by the dev of Amethyst Imbuement to come here.

https://github.com/fzzyhmstrs/ai/issues/17

**Comment by TheRealHenHen** [comment]
So, there is a compatibility issue with Amethyst Imbuement?

**Comment by Sunconure11** [comment]
Yes, and it’s related to mixins.

**Comment by TheRealHenHen** [comment]
Okay, I'll look into it

**Comment by Sunconure11** [comment]
This is on 1.18.2, keep that in mind

**Comment by TheRealHenHen** [comment]
Fixed! An update (v1.0.1) will be released soon
