### ISSUE TITLE
YDM Compatibility

### ISSUE THREAD

**Issue by ardissaps** [TheRealHenHen/Bamboo-Combat#2]
The weapon rendered weirdly with [YDM Weapon Master](https://modrinth.com/mod/weaponmaster)

**Comment by TheRealHenHen** [comment]
Can't be fixed because the source code of [YDM Weapon Master](https://modrinth.com/mod/weaponmaster) required to fix the bug cannot be accessed. I may come back to this issue once the source code goes public.
