### ISSUE TITLE
Renderer mixin in common section

### ISSUE THREAD

**Issue by Linguardium** [TheRealHenHen/Bamboo-Combat#5]
https://github.com/TheRealHenHen/Bamboo-Combat/blob/914abfd072d47b80300a3f2fb4a0fac7f47264e1/src/main/resources/bamboocombat.mixins.json#L10

This mixin should be in the client section of the config to ensure it doesnt attempt to run on the server (since renderers and renderer code doesnt exist on servers)

**Comment by TheRealHenHen** [comment]
Thank you
